# .github/workflows/lint.yml

name: Lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install dependancies
        uses: bundle install

      - name: Code Checkout
        uses: make lint
